version: '3'
services:
  webapp:
    build: .
    volumes:
      - .:/webemail
    ports:
      - 3000:3000
    entrypoint: sh /webemail/scripts/commandfile.sh
    links:
      - db
  db:
    image: postgres
    ports:
      - 7000:5432
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=web
